/***************************************************/
// Author:Panyg     AUTO GENERATED BY ANT 
// lichen Build = 0.0.1
// File : src\main\java\com\surfilter\Project.java

package com.surfilter;

import java.util.Date;

public class Project
{
 static  public String getBuildVersion() { return "0.0.1"; }
 static  public String getBuildNumber() {return "1";}
 static  public String getVersion() {return "0";}
 static  public String getRevision() {return "0";}
 static  public String getBuildDate() {return "Wed Nov 27 16:37:55 CST 2013";}
}
/******************** END OF FILE ***************/

