/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-14 08:32:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.iscore;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class monitorResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<title>机房信息</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \t\r\n");
      out.write("</head>\r\n");
      out.write("<body  class=\"easyui-layout\" fit=\"true\">\r\n");
      out.write("\t<div region=\"north\" class=\"breadCrumb-min\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!--  搜索条件 -->\r\n");
      out.write("\t\t<div class=\"search-left\">\r\n");
      out.write("\t\t\t<form id=\"queryForm\">\r\n");
      out.write("\t\t\t<div class=\"search-form runDetail-form windowpop\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"strategyId\" name=\"strategyId\" value=\"");
      out.print(request.getParameter("strategyId"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"returnPage\" name=\"returnPage\" value=\"");
      out.print(request.getParameter("returnPage"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"eventCode\" value=\"");
      out.print(request.getParameter("eventCode"));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"bussType\" value=\"");
      out.print(request.getParameter("bussType"));
      out.write("\">\r\n");
      out.write("\t\t\t\t   \t<span>客户端主机IP： <input name=\"srcIp\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t\t\t\t<span style=\"display: none\">目的主机IP： <input name=\"destIp\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t\t\t\t<span>URL： <input  id=\"url\" name=\"url\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t\t\t\t<span>访问开始时间： <input  name=\"collectTimeBefore\" type=\"text\" class=\"easyui-datetimebox\" class=\"input-big\"></span>\r\n");
      out.write("\t\t\t\t\t<span>访问结束时间 ： <input  name=\"collectTimeAfter\" type=\"text\" class=\"easyui-datetimebox\" class=\"input-big\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"search-button\"><a class=\"linkbutton\" href=\"javascript:void(0)\" id=\"searchSynthMonitorResult\">查询</a></span> \r\n");
      out.write("\t\t<!-- \t<a class=\"linkbutton\" href=\"javascript:void(0)\" fileName=\"searchSynthMonitorRunDetail\" exportExcel=\"monitorResultGrid\" type=\"export\" formId=\"queryForm1\" id=\"exportSpeIpLineMonitorRunDetail\" plain=\"true\"><span class=\"export\"></span>导出</a>\r\n");
      out.write("\t\t --></div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!--  面包屑 -->\t\t\r\n");
      out.write("\t \t<div class=\"search-right\">\r\n");
      out.write("\t   \t\t<span class=\"crumbs\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/menuNav.jsp", out, false);
      out.write("</span>\r\n");
      out.write("\t\t\t<span class=\"full\"><a href=\"javascript:void(0);\"></a></span>\r\n");
      out.write("<!-- \t\t\t<span class=\"return\"><a href=\"javascript:void(0);\"></a></span> -->\r\n");
      out.write("\t \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  列表 -->\t\r\n");
      out.write("\t<div data-options=\"region:'center'\" class=\"listCenter\" style=\"height:500px\">\r\n");
      out.write("\t\t<table id=\"monitorResultGrid\" >\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modules/iscore/monitorResult.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
