/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-16 12:02:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<title>机房信息</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/test/test.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugs/easyui-expands/datagrid-detailview1.js\"></script>\r\n");
      out.write("   \t\r\n");
      out.write("</head>\r\n");
      out.write("<body  class=\"easyui-layout\">\r\n");
      out.write("\t<!-- 查询条件 -->\r\n");
      out.write("\t<div region=\"north\" class=\"breadCrumb-max\">\r\n");
      out.write("\t\t<!-- 查询条件 -->\r\n");
      out.write("\t\t<div class=\"search-left\">\r\n");
      out.write("\t\t\t<span class=\"search-ico\"></span>\r\n");
      out.write("\t\t\t<h1 class=\"search-title\">内容搜索</h1>\r\n");
      out.write("\t\t\t<form id=\"queryForm\">\r\n");
      out.write("\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t   \t<span>网站名称  <input name=\"siteName\" id=\"siteName\" type=\"text\" class=\"input-text\"></span>\r\n");
      out.write("\t\t\t\t<span>主办单位 <input name=\"sponsor\" id=\"sponsor\" type=\"text\" class=\"input-text\"></span>\r\n");
      out.write("\t\t\t\t<span>信任级别 <input name=\"trustLevel\" id=\"trustLevel\" type=\"text\" class=\"input-text\"></span>\r\n");
      out.write("\t\t\t\t<span>有效状态 \r\n");
      out.write("\t\t\t\t\t<input  id=\"state\" name=\"state\" type=\"text\" class=\"input-text\">\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<span class=\"search-button\"><a href=\"javascript:void(0)\" id=\"searchTest\">搜索</a></span> \r\n");
      out.write("\t\t\t\t<span class=\"search-button search-gj\"><a href=\"javascript:void(0)\" id=\"searchTestAdvance\">高级搜索</a></span> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--  面包屑 -->\r\n");
      out.write("\t\t<div class=\"search-right\">\r\n");
      out.write("    \t\t<span class=\"crumbs\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/menuNav.jsp", out, false);
      out.write("</span>\r\n");
      out.write("\t\t\t<span class=\"full\"><a href=\"javascript:void(0);\"></a></span>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<!-- add -->\r\n");
      out.write("\t\t<div class=\"list-add list-add-float\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"addTest\"><span class=\"add\"></span>新增</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"delTest\"><span class=\"del\"></span>删除</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"startTest\"><span class=\"start\"></span>启用</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"stopTest\"><span class=\"stop\"></span>停用</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" fileName=\"test\" exportExcel=\"testGrid\" type=\"export\" formId=\"queryForm\" id=\"exportTest\" plain=\"true\"><span class=\"export\"></span>导出</a>\r\n");
      out.write("\t \t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'center'\">\r\n");
      out.write("\t\t<table id=\"testGrid\" >\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"detailDiv\" class=\"list-load\" style=\"width: 100%;display: none;\">\r\n");
      out.write("\t\t<div class=\"list-detail\">\r\n");
      out.write("\t\t\t<form id=\"testDetailForm\">\r\n");
      out.write("\t\t\t\t<table class=\"list-detail-table\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>网站负责人:</th> <td><input class=\"nosign\"  name=\"principal\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>网站首页:</th><td><input class=\"nosign\" name=\"siteHomeUrl\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>有效证件类型:</th><td><input class=\"nosign\" id=\"papersType\" name=\"papersType\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>有效证件号码:</th><td><input class=\"nosign\"  name=\"papersNum\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>手机号码:</th><td><input class=\"nosign\"  name=\"telPhone\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>电子邮箱:</th><td><input class=\"nosign\"  name=\"email\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>办公室号码:</th><td><input class=\"nosign\"  name=\"officePhone\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>添加时间:</th><td><input class=\"nosign\" name=\"createTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>备注:</th><td><input class=\"nosign\" name=\"remark\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"advanceSearch-dlg\" style=\"width:600px;\">\r\n");
      out.write("\t\t<!-- 基本信息 -->\r\n");
      out.write("\t\t<form id=\"advancedQueryForm\"  method=\"post\">\r\n");
      out.write("\t\t<div class=\"easyui-panel\" >\r\n");
      out.write("\t\t\t<!-- 添加 -->\r\n");
      out.write("\t\t\t<div class=\"add-table add-list2\">\r\n");
      out.write("\t\t    \t<table  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">网站名称：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"siteName\" type=\"text\" class=\"input-text\" /></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">主办单位：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"sponsor\" type=\"text\" class=\"input-text\" /></input></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">信任级别：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input  id=\"trustLevelAdvance\" name=\"trustLevel\" type=\"text\" class=\"input-text\"></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">有效状态：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input  id=\"stateAdvance\" name=\"state\" type=\"text\" class=\"input-text\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">域名：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"domain\" type=\"text\" class=\"input-text\"></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">网站类别：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"siteType\" type=\"text\" class=\"input-text\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">创建起始时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"createTimeBefore\" type=\"text\" class=\"easyui-datebox\" editable=\"false\"></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">创建截止时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"createTimeAfter\" type=\"text\" class=\"easyui-datebox\" editable=\"false\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"add-save\">\r\n");
      out.write("\t\t   \t<a href=\"javascript:void(0);\" id=\"advanceSearchSubmit\" class=\"easyui-linkbutton\" >搜索</a>\r\n");
      out.write("\t\t   \t<!--<a href=\"javascript:void(0);\" id=\"advanceSearchReset\" class=\"easyui-linkbutton\" >重置</a>-->\r\n");
      out.write("\t\t   \t<a href=\"javascript:void(0);\" id=\"advanceSearchCancel\" class=\"easyui-linkbutton\" onclick=\"javascript:$('#advanceSearch-dlg').dialog('close')\">关闭</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/excel.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
