/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-16 10:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\"content=\"IE=9; IE=8; IE=7; IE=EDGE\">\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("<title>欢迎使用");
      out.print(request.getSession().getServletContext().getInitParameter("smcsCnName") );
      out.write("</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"js/easyui/themes/rzx-ui/images/favicon.ico\" />\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/plugs/autoComplete/jquery.autocomplete.css\"></link>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/sysui/css/clock/clock.css\"></link>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/message.js\"></script>\r\n");
      out.write("<!---->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/autoComplete/jquery.autocomplete.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/globalsearch.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/easyui-expands/datagrid-detailview1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).ajaxComplete(function(event, xhr, options){\r\n");
      out.write("\tvar text = xhr.responseText;\r\n");
      out.write("\tif(text.indexOf(\"{\")==0){\r\n");
      out.write("\t\tvar data = $.parseJSON(text);\r\n");
      out.write("\t\t\r\n");
      out.write("//\t\tconsole.log(\"data:\" + data);\r\n");
      out.write("\t\tif(data.errorCode == '602'){\r\n");
      out.write("\t\t\t$.messager.show({\r\n");
      out.write("                title:'系统访问权限提示',\r\n");
      out.write("                msg:data.message,\r\n");
      out.write("                timeout:6000,\r\n");
      out.write("                showType:'slide'\r\n");
      out.write("            });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).keyup(function(event){\r\n");
      out.write("\t\t//alert(event.keyCode);\r\n");
      out.write("\t\t /*  if(event.keyCode ==13){\r\n");
      out.write("\t\t\t  $(\"#ok\").click();\r\n");
      out.write("\t\t  } */\r\n");
      out.write("\t\t  \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#globalsearch\").keyup(function(){\r\n");
      out.write("\t\tvar text=$(this).val(); \r\n");
      out.write("\t\tif(!text){\r\n");
      out.write("\t\t\t$(this).removeClass(\"input-warning\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("    $(\".top-close\").hide();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#globalsearch\").keyup(function(){\r\n");
      out.write("\t\tvar zz = $(\"#globalsearch\");\r\n");
      out.write("\t\tif(zz.length>0){\r\n");
      out.write("\t\t\t $(\".top-close\").show();\r\n");
      out.write("\t\t} \r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t$(\".top-close\").bind(\"click\",function(){\r\n");
      out.write("\t\t$(\"#globalsearch\").val(\"\");\r\n");
      out.write("\t\t$(this).hide();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t})\r\n");
      out.write("\t\t \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<body class=\"easyui-layout\" border=\"false\">\r\n");
      out.write("<div class=\"setting\" title=\"设置皮肤\" onclick=\"initSysSyle()\"></div>\r\n");
      out.write("<div class=\"side_right\">\r\n");
      out.write("\t<ul class=\"skin_head_ico\">\r\n");
      out.write("\t\t<li id=\"li_version_h\"><a href=\"javascript:void(0);\"  onclick=\"aboutme()\" class=\"skin-tool skin-tool-resource\"  title=\"版本信息\"></a></li>                                                                         \r\n");
      out.write("\t\t<li id=\"li_msg_h\"><a href=\"javascript:void(0);\"  onclick=\"showMsg()\" class=\"skin-tool skin-tool-msg\" title=\"短信息\"><span class=\"msg-num\"><b type=\"msgnum\" >0</b></span></a></li>\r\n");
      out.write("\t\t<li><a href=\"javascript:void(0);\"  onclick=\"updatePwd()\" class=\"skin-tool skin-tool-set\"  title=\"密码修改\"></a></li>\r\n");
      out.write("\t\t<li id=\"li_szpf_h\"><a href=\"javascript:void(0);\"  onclick=\"initSysSyle()\" class=\"skin-tool skin-tool-szpf\"  title=\"设置皮肤\"></a></li>\r\n");
      out.write("\t\t<li><a href=\"javascript:void(0);\"  onclick=\"logout()\" class=\"skin-tool skin-tool-exit\"  title=\"退出\"></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div region=\"north\" border=\"false\" class=\"skin_head\" split=\"false\">\r\n");
      out.write("     <div class=\"skin_head_top\">\r\n");
      out.write("         <span class=\"skin_head_wel\">欢迎您：<span>");
      out.print(request.getSession().getAttribute("userName") );
      out.write("!</span></span>\r\n");
      out.write("         <ul class=\"skin_head_ico\">\r\n");
      out.write("         \t <li id=\"li_version_r\"><a href=\"javascript:void(0);\"  onclick=\"aboutme()\" class=\"skin-tool skin-tool-resource\"  title=\"版本信息\"></a></li>                                                                        \r\n");
      out.write("             <li id=\"li_msg_r\"><a href=\"javascript:void(0);\"  onclick=\"showMsg()\" class=\"skin-tool skin-tool-msg\" title=\"短信息\"><span class=\"msg-num\"><b type=\"msgnum\" >0</b></span></a></li>\r\n");
      out.write("             <li><a href=\"javascript:void(0);\"  onclick=\"updatePwd()\" class=\"skin-tool skin-tool-set\"  title=\"密码修改\"></a></li>\r\n");
      out.write("             <li id=\"li_szpf_r\"><a href=\"javascript:void(0);\"  onclick=\"initSysSyle()\" class=\"skin-tool skin-tool-szpf\"  title=\"设置皮肤\"></a></li>\r\n");
      out.write("             <li><a href=\"javascript:void(0);\"  onclick=\"logout()\" class=\"skin-tool skin-tool-exit\"  title=\"退出\"></a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"skin_head_logo\">\r\n");
      out.write("         <div class=\"logo\"><img  src=\"");
      out.print(request.getSession().getAttribute("logo") );
      out.write("\"></div>\r\n");
      out.write(" \t\t<div class=\"pullDown\">\r\n");
      out.write("       \t\t<ul class=\"pullDownList\">\r\n");
      out.write("       \t\t</ul>\r\n");
      out.write("       \t\t<!-- 下拉详细列表具体分类 -->\r\n");
      out.write("       \t\t<div class=\"yMenuListCon\">\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div region=\"west\" border=\"false\"  split=\"false\" class=\"skins_left\">\r\n");
      out.write("<div class=\"skin_left\">\r\n");
      out.write("    <div class=\"pullDown\">\r\n");
      out.write("        <ul class=\"pullDownList\">\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- 下拉详细列表具体分类 -->\r\n");
      out.write("        <div class=\"yMenuListCon\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>  \r\n");
      out.write("</div>\r\n");
      out.write("<div region=\"center\" border=\"false\" class=\"skin_center\" split=\"false\">\r\n");
      out.write("<div  class=\"easyui-layout\" fit=\"true\">\r\n");
      out.write("\t<div region=\"north\" border=\"false\" >\r\n");
      out.write("\t\t<div class=\"breadcrumbs\">\r\n");
      out.write("        <ul class=\"breadcrumb\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <i class=\"icon-home\"></i>\r\n");
      out.write("                <i id=\"breadMenu\"><!-- <a href=\"javascript:void(0);\">信息安全</a> > <a href=\"javascript:void(0);\">日常监测</a> --></i>\r\n");
      out.write("                \r\n");
      out.write("            </li>\r\n");
      out.write("            <!-- <li class=\"active\">>监测任务管理</li> -->\r\n");
      out.write("        </ul>\r\n");
      out.write("        <span class=\"skin_head_wel\">欢迎您：<span>");
      out.print(request.getSession().getAttribute("userName") );
      out.write("!</span></span>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div region=\"center\" border=\"false\" id=\"mainPanel\">\r\n");
      out.write("    \t<iframe win=\"show\" style=\"background-color: white;\" height=\"100%\" width=\"100%\" scrolling=\"auto\"  id=\"f_House\" name=\"f_House\"  frameborder=\"0\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"searchTop-drop\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li>业务</li>\r\n");
      out.write("\t\t\t<li>菜单</li>\r\n");
      out.write("\t\t\t<li>网页</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" id=\"ukeynum\" value=\"");
      out.print(request.getSession().getAttribute("ukeyNum") );
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"usertype\" value=\"");
      out.print(request.getSession().getAttribute("userType") );
      out.write("\"/>\r\n");
      out.write("\t<input type=\"hidden\" id=\"crrentdiverpath\" value=\"");
      out.print(request.getSession().getAttribute("crrentdiverpath") );
      out.write("\"/>\r\n");
      out.write("\t<object type=\"application/x-dongle\" id=\"don\" width=\"0\" height=\"0\"></object>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
