/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-13 11:10:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class timeout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" /> \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<title>哎呀...超时了！</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("*{margin:0;padding:0}\r\n");
      out.write("body{font-family:\"微软雅黑\";background:#DAD9D7}\r\n");
      out.write("img{border:none}\r\n");
      out.write("a *{cursor:pointer}\r\n");
      out.write("ul,li{list-style:none}\r\n");
      out.write("table{table-layout:fixed;}\r\n");
      out.write("table tr td{word-break:break-all; word-wrap:break-word;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".cf:after{content: \".\";display: block;height: 0;font-size: 0;clear:both;visibility: hidden;}\r\n");
      out.write(".cf{zoom: 1;clear:both}\r\n");
      out.write("\r\n");
      out.write(".bg{width:100%;background:url(\"resources/images/timeout/01.jpg\") no-repeat center top #DAD9D7;position:absolute;top:0;left:0;height:600px;overflow:hidden}\r\n");
      out.write(".cont{margin:0 auto;width:500px;line-height:20px;}\r\n");
      out.write(".c1{height:360px;text-align:center}\r\n");
      out.write(".c1 .img1{margin-top:180px}\r\n");
      out.write(".c1 .img2{margin-top:165px}\r\n");
      out.write(".cont h2{text-align:center;color:#555;font-size:18px;font-weight:normal;height:35px}\r\n");
      out.write(".c2{height:35px;text-align:center}\r\n");
      out.write(".c2 a{display:inline-block;margin:0 4px;font-size:14px;height:23px;color:#626262;padding-top:1px;text-decoration:none;text-align:left}\r\n");
      out.write(".c2 a:hover{color:#626262;text-decoration:none;}\r\n");
      out.write(".c2 a.home{width:66px;background:url(\"resources/images/timeout/02.png\");padding-left:30px}\r\n");
      out.write(".c2 a.home:hover{background:url(\"resources/images/timeout/02.png\") 0 -24px}\r\n");
      out.write(".c2 a.home:active{background:url(\"resources/images/timeout/02.png\") 0 -48px}\r\n");
      out.write(".c2 a.re{width:66px;background:url(\"resources/images/timeout/03.png\");padding-left:30px}\r\n");
      out.write(".c2 a.re:hover{background:url(\"resources/images/timeout/03.png\") 0 -24px}\r\n");
      out.write(".c2 a.re:active{background:url(\"resources/images/timeout/03.png\") 0 -48px}\r\n");
      out.write(".c2 a.sr{width:153px;background:url(\"resources/images/timeout/04.png\");padding-left:28px}\r\n");
      out.write(".c2 a.sr:hover{background:url(\"resources/images/timeout/04.png\") 0 -24px}\r\n");
      out.write(".c2 a.sr:active{background:url(\"resources/images/timeout/04.png\") 0 -48px}\r\n");
      out.write(".c3{height:180px;text-align:center;color:#999;font-size:12px}\r\n");
      out.write("#bf{position:absolute;top:269px;left:0;width:100%}\r\n");
      out.write(".bf1{margin:0 auto;width:99px;padding-left:32px}\r\n");
      out.write(".bd{height:600px;overflow:hidden}\r\n");
      out.write("#box{position:absolute;top:165px;left:0;width:100%;text-align:center}\r\n");
      out.write(".bf1{margin:0 auto;width:99px;padding-left:32px}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"hidden\" id=\"basePath\" value=\"");
      out.print(basePath);
      out.write("\"/>\r\n");
      out.write("<div class=\"bg\">\r\n");
      out.write("\t<div class=\"cont\">\r\n");
      out.write("\t\t<div class=\"c1\"><img src=\"resources/images/timeout/01.png\" class=\"img1\" /></div>\r\n");
      out.write("\t\t<h2>由于您长时间没有操作，需要重新登录<a href=\"");
      out.print(basePath);
      out.write("\" >返回登录</a></h2>\r\n");
      out.write("\t\t<div class=\"c2\"></div>\r\n");
      out.write("\t\t<div class=\"c3\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
