/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-15 12:13:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upAndDown_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<div class=\"set_main\">\r\n");
      out.write("<div class=\"set_tops\">\r\n");
      out.write("     <h3 class=\"set_head\">设置logo及菜单图标</h3>\r\n");
      out.write("    <div class=\"set_top\">\r\n");
      out.write("        <div class=\"set_top_l\">\r\n");
      out.write("        <img id=\"setLogoUpId\" src=\"js/sysui/images/set_logo.png\" class=\"set_logo\">\r\n");
      out.write("        <div class=\"logo_div\">\r\n");
      out.write("            <ul>\r\n");
      out.write("            <div id=\"logo\">\r\n");
      out.write("                <!-- <li><a href=\"javascript:void(0);\" onclick=\"editLogo('upAnDown','1')\" id=\"test\"><img src=\"js/sysui/images/set_logo.png\"></a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"editLogo('upAnDown','2')\"><img src=\"js/sysui/images/set_logo.png\"></a></li> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("       <!--  <img src=\"js/sysui/images/arrow_r.png\" class=\"arrow_r\"> -->\r\n");
      out.write("       <!--  <span class=\"logo_span\">点击设置logo</span> -->\r\n");
      out.write("       </div>\r\n");
      out.write("        <div class=\"set_nav2\">\r\n");
      out.write("       <!--  <div class=\"nav_arrow2\"><img src=\"js/sysui/images/arrow_t3.jpg\" class=\"arrow_t1\"><span>设置菜单图标</span></div> -->\r\n");
      out.write("        <ul class=\"set_nav_list2\">\r\n");
      out.write("          <div id=\"upId\">\r\n");
      out.write("            <!-- <li>\r\n");
      out.write("                <a href=\"javascript:void(0);\"><span class=\"nav_span\">行业管理</span><img id=\"setHyUpId\" src=\"js/sysui/images/set_nav.png\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:void(0);\"><span class=\"nav_span\">信息安全</span><img id=\"setXxUpId\" src=\"js/sysui/images/set_nav.png\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:void(0);\"><span class=\"nav_span\">网络安全</span><img id=\"setWlUpId\" src=\"js/sysui/images/set_nav.png\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:void(0);\"><span class=\"nav_span\">应急协查</span><img id=\"setYjUpId\" src=\"js/sysui/images/set_nav.png\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:void(0);\"><span class=\"nav_span\">系统管理</span><img id=\"setXtUpId\" src=\"js/sysui/images/set_nav.png\"></a>\r\n");
      out.write("            </li> -->\r\n");
      out.write("           </div> \r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <!--菜单弹出-->\r\n");
      out.write("        <div class=\"nav_choose2\">\r\n");
      out.write("            <div class=\"nav_div2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <div id=\"hy\">\r\n");
      out.write("                    <!-- <li><a href=\"javascript:void(0);\" onclick=\"editHy('upAnDown','1')\"><img src=\"js/sysui/images/hygl/hygl_1.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editHy('upAnDown','2')\"><img src=\"js/sysui/images/hygl/hygl_2.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editHy('upAnDown','3')\"><img src=\"js/sysui/images/hygl/hygl_3.png\"></a></li> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"nav_div2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                 <div id=\"wl\">\r\n");
      out.write("                   <!--  <li><a href=\"javascript:void(0);\" onclick=\"editWl('upAnDown','1')\"><img src=\"js/sysui/images/wlaq/wlaq_1.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editWl('upAnDown','2')\"><img src=\"js/sysui/images/wlaq/wlaq_2.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editWl('upAnDown','3')\"><img src=\"js/sysui/images/wlaq/wlaq_3.png\"></a></li> -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav_div2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                 <div id=\"xx\">\r\n");
      out.write("                   <!--  <li><a href=\"javascript:void(0);\" onclick=\"editXx('upAnDown','1')\"><img src=\"js/sysui/images/xxaq/xxaq_1.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editXx('upAnDown','2')\"><img src=\"js/sysui/images/xxaq/xxaq_2.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editXx('upAnDown','3')\"><img src=\"js/sysui/images/xxaq/xxaq_3.png\"></a></li> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav_div2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                 <div id=\"yj\">\r\n");
      out.write("                    <!-- <li><a href=\"javascript:void(0);\" onclick=\"editYj('upAnDown','1')\"><img src=\"js/sysui/images/yjxc/yjxc_1.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editYj('upAnDown','2')\"><img src=\"js/sysui/images/yjxc/yjxc_2.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editYj('upAnDown','3')\"><img src=\"js/sysui/images/yjxc/yjxc_3.png\"></a></li> -->\r\n");
      out.write("                <div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"nav_div2\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                <div id=\"xt\">\r\n");
      out.write("                    <!-- <li><a href=\"javascript:void(0);\" onclick=\"editXt('upAnDown','1')\"><img src=\"js/sysui/images/xtgl/xtgl_1.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editXt('upAnDown','2')\"><img src=\"js/sysui/images/xtgl/xtgl_2.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:void(0);\" onclick=\"editXt('upAnDown','3')\"><img src=\"js/sysui/images/xtgl/xtgl_3.png\"></a></li> -->\r\n");
      out.write("                </div>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"set_center\">\r\n");
      out.write("        <div class=\"set_colors set_color2\">\r\n");
      out.write("         <h3 class=\"set_head\">设置皮肤</h3>\r\n");
      out.write("        <div class=\"set_color\">\r\n");
      out.write("            <ul class=\"color_list\">\r\n");
      out.write("               <div id=\"skin\">\r\n");
      out.write("               <!--  <li><a href=\"javascript:void(0);\" onclick=\"editPf('upAnDown','1')\" class=\"color_1\"></a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"editPf('upAnDown','2')\" class=\"color_2\"></a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"editPf('upAnDown','3')\" class=\"color_3\"></a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"editPf('upAnDown','4')\" class=\"color_4\"></a></li>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"editPf('upAnDown','5')\" class=\"color_5\"></a></li> -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </ul>\r\n");
      out.write("           <!--  <div class=\"nav_arrow3\"><img src=\"js/sysui/images/arrow_t1.jpg\" class=\"arrow_t1\"><span>设置皮肤</span></div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</html>\r\n");
      out.write("<input type=\"hidden\" name=\"syleTypeUpAndDownId\" id=\"syleTypeUpAndDownId\" value='");
      out.print(request.getParameter("flag"));
      out.write("'/>\r\n");
      out.write("<input type=\"hidden\" name=\"userType\" id=\"userType\" value='");
      out.print(request.getSession().getAttribute("userType"));
      out.write("'/>\t\r\n");
      out.write(" <script type=\"text/javascript\" src=\"js/modules/system/skin.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
