/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-15 07:15:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.isapp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dnsDomainMonitor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<title>机房信息</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugs/easyui-expands/datagrid-detailview1.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/common/business.js\"></script>\r\n");
      out.write("   \t<script type=\"text/javascript\" src=\"js/modules/iscore/iscommon.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/isapp/dnsDomainMonitor.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body  class=\"easyui-layout\" fit=\"true\">\r\n");
      out.write("\r\n");
      out.write("\t<div region=\"north\" class=\"breadCrumb-max\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t <!--  搜索条件 -->\r\n");
      out.write("\t\t<div class=\"search-left\">\r\n");
      out.write("\t\t\t<span class=\"search-ico\"></span>\r\n");
      out.write("\t\t\t<h1 class=\"search-title\">内容搜索</h1>\r\n");
      out.write("\t\t\t<form id=\"queryForm\">\r\n");
      out.write("\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"businessType\"/>\r\n");
      out.write("\t\t\t\t   \t<span>策略名称 ： <input name=\"strategyName\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t\t\t\t<span>域名：  <input name=\"domain\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t\t\t\t<span>运行状态 ： <input  id=\"strategyState\" name=\"strategyState\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t\t\t\t<!-- <span>审核状态：<input  id=\"auditState\" name=\"auditState\" type=\"text\" class=\"input-small\"></span> -->\r\n");
      out.write("\t\t\t\t\t<span class=\"search-button\"><a href=\"javascript:void(0)\" id=\"searchDnsDomainMonitor\">查询</a></span> \r\n");
      out.write("\t\t\t\t\t<span class=\"search-button search-gj\"><a href=\"javascript:void(0)\" id=\"searchDnsDomainMonitorAdvanced\">高级查询</a></span>   \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!--  面包屑 -->\t\t\r\n");
      out.write("\t \t<div class=\"search-right\">\r\n");
      out.write("    \t\t<span class=\"crumbs\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/menuNav.jsp", out, false);
      out.write("</span>\r\n");
      out.write("\t\t\t<span class=\"full\"><a href=\"javascript:void(0);\"></a></span>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\t<!--  列表多选操作 -->\r\n");
      out.write("\t\t<div class=\"list-add\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\"  id=\"add\"><span class=\"add\"></span>新增</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\" id=\"del\"><span class=\"del\"></span>删除</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\"  id=\"audit\"><span class=\"audit\"></span>审核</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\"  id=\"start\"><span class=\"start\"></span>启动</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\"  id=\"stop\"><span class=\"stop\"></span>停止</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" fileName=\"dnsDomainMoitor\" exportExcel=\"dnsDomainMonitorGrid\" type=\"export\" formId=\"queryForm\" id=\"exportDnsDomainMonitor\" plain=\"true\"><span class=\"export\"></span>导出</a>\r\n");
      out.write("\t \t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--  列表 -->\t\r\n");
      out.write("    <div region=\"center\" class=\"listCenter\">\r\n");
      out.write("\t\t<table id=\"dnsDomainMonitorGrid\" >\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"detailDiv\" class=\"list-load\" style=\"width: 100%;display: none;\">\r\n");
      out.write("\t\t<div class=\"list-detail\">\r\n");
      out.write("\t\t\t<form id=\"domainMonitorDetailForm\">\r\n");
      out.write("\t\t\t\t<table class=\"list-detail-table\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>策略名称:</th> <td><input class=\"nosign\"  name=\"strategyName\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t<th>域名:</th><td><input class=\"nosign\" name=\"domain\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t<th>监测结果总量:</th><td><input class=\"nosign\" name=\"visitCount\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>生效时间:</th><td><input class=\"nosign\"  name=\"effectTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t<th>过期时间:</th><td><input class=\"nosign\"  name=\"pastTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t<th>创建人:</th><td><input class=\"nosign\"  name=\"createUser\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>创建时间:</th><td><input class=\"nosign\"  name=\"createTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t<th>备案号:</th><td><input class=\"nosign\" name=\"licenseKey\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t<th>是否黑名单:</th><td><input class=\"nosign\" name=\"isBlack\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id=\"advanceSearch-dlg\">\r\n");
      out.write("\t\t<!-- 基本信息 -->\r\n");
      out.write("\t\t<form id=\"advancedQueryForm\"  method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"businessType\" />\r\n");
      out.write("\t\t\t<!-- 添加 -->\r\n");
      out.write("\t\t\t<div class=\"add-table add-list2\">\r\n");
      out.write("\t\t    \t<table  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">策略名称：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"strategyName\" type=\"text\" class=\"input-big\" /></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">域名：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"domain\" type=\"text\" class=\"input-big\" /></input></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">运行状态：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input  id=\"strategyStateAdvance\" name=\"strategyState\" type=\"text\" class=\"input-big\"></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">操作人：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"createUser\" type=\"text\" class=\"input-big\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">生效起始时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"effectTimeBefore\" type=\"text\" class=\"easyui-datebox input-big\" editable=\"false\"></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">生效截止时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"effectTimeAfter\" type=\"text\" class=\"easyui-datebox input-big\" editable=\"false\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">过期起始时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"pastTimeBefore\" type=\"text\" class=\"easyui-datebox input-big\" editable=\"false\"></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">过期截止时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"pastTimeAfter\" type=\"text\" class=\"easyui-datebox input-big\" editable=\"false\"></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"add-save\">\r\n");
      out.write("\t\t   \t<a href=\"javascript:void(0);\" id=\"advanceSearchSubmit\" class=\"easyui-linkbutton\" >查询</a>\r\n");
      out.write("\t\t   <!--\t<a href=\"javascript:void(0);\" id=\"advanceSearchReset\" class=\"easyui-linkbutton\" >重置</a>-->\r\n");
      out.write("\t\t   \t<a href=\"javascript:void(0);\" id=\"advanceSearchCancel\" class=\"easyui-linkbutton\" onclick=\"javascript:$('#advanceSearch-dlg').dialog('close')\">关闭</a>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/excel.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
