/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-15 07:19:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.isapp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class webBrowseFilter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<title>网页精确冻结</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/common/business.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/iscore/iscommon.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/isapp/webBrowseFilter.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugs/easyui-expands/datagrid-detailview1.js\"></script>\r\n");
      out.write("   \t\r\n");
      out.write("</head>\r\n");
      out.write("<body  class=\"easyui-layout\" fit=\"true\">\r\n");
      out.write("\r\n");
      out.write("<div region=\"north\" class=\"breadCrumb-max\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 查询条件 -->\r\n");
      out.write("\t<div class=\"search-left\">\r\n");
      out.write("\t\t<span class=\"search-ico\"></span>\r\n");
      out.write("\t\t<h1 class=\"search-title\">内容搜索</h1>\r\n");
      out.write("\t\t<form id=\"queryForm\">\r\n");
      out.write("\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"businessType\"/>\r\n");
      out.write("\t\t\t<span><label class=\"label4\">策略名称：</label><input class=\"input-small\" name=\"strategyName\" id=\"strategyName\" type=\"text\"></span>\r\n");
      out.write("\t\t\t<span><label class=\"label6\">域名/URL/IP：</label><input class=\"input-small\" name=\"webPage\" type=\"text\"></span>\r\n");
      out.write("\t\t\t<span><label class=\"label4\">运行状态：</label><input class=\"input-small\" name=\"strategyState\" id=\"strategyState\"type=\"text\"></span>\r\n");
      out.write("\t\t\t<span class=\"search-button\"><a href=\"javascript:void(0)\" id=\"searchPageAccurateFilter\">查询</a></span>\r\n");
      out.write("\t\t\t<span class=\"search-button search-gj\"><a href=\"javascript:void(0)\" id=\"advanceSearch\">高级查询</a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t </div>  \r\n");
      out.write("\t    \r\n");
      out.write("\t    <!--  面包屑 -->\r\n");
      out.write("\t\t<div class=\"search-right\">\r\n");
      out.write("    \t\t<span class=\"crumbs\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/menuNav.jsp", out, false);
      out.write("</span>\r\n");
      out.write("\t\t\t<span class=\"full\"><a href=\"javascript:void(0);\"></a></span>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!--  列表多选操作 -->\r\n");
      out.write("\t\t<div class=\"list-add\">\r\n");
      out.write("  \t\t\t<a href=\"javascript:void(0)\" id=\"add\"><span class=\"add\"></span>新增</a>\r\n");
      out.write("  \t\t\t<a href=\"javascript:void(0);\" id=\"del\"><span class=\"del\"></span>删除</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"audit\"><span class=\"audit\"></span>审核</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"start\"><span class=\"start\"></span>启动</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" id=\"stop\"><span class=\"stop\"></span>停止</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 列表-->\r\n");
      out.write("\t<div region=\"center\" class=\"listCenter\">\r\n");
      out.write("\t\t<table id=\"pageAccurateFilterGrid\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 列表详细-->\r\n");
      out.write("\t<div id=\"detailDiv\" class=\"list-load\">\r\n");
      out.write("\t\t<div class=\"list-detail\">\r\n");
      out.write("\t\t\t<form id=\"pageAccurateFilterDetailForm\">\r\n");
      out.write("\t\t\t\t<table class=\"list-detail-table\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>策略名称:</th> <td><input class=\"nosign\"  name=\"strategyName\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>域名/URL/IP:</th><td><input class=\"nosign\" name=\"webPage\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>冻结请求次数:</th><td><input class=\"nosign\" name=\"visitCount\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>创建时间:</th><td><input class=\"nosign\"  name=\"createTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>生效时间:</th><td><input class=\"nosign\"  name=\"effectTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>过期时间:</th><td><input class=\"nosign\"  name=\"pastTime\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>是否记录日志:</th><td><input class=\"nosign\"  name=\"logDesc\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t\t<th>创建人:</th><td><input class=\"nosign\"  name=\"createUser\" readonly=\"readonly\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 高级搜索  start -->\r\n");
      out.write("\t<div id=\"advanceSearch-dlg\" style=\"width:600px;\">\r\n");
      out.write("\t\t<!-- 基本信息 -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"easyui-panel\" >\r\n");
      out.write("\t\t\t<!-- 添加 -->\r\n");
      out.write("\t\t\t<form id=\"advancedQueryForm\"  method=\"post\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"businessType\"/>\r\n");
      out.write("\t\t\t<div class=\"add-table add-list2\">\r\n");
      out.write("\t\t    \t<table  width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">策略名称：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input class=\"input-big\" name=\"strategyName\" type=\"text\"></input></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">任务状态：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input class=\"input-big\" name=\"strategyState\" id=\"strategyStateAdvance\" type=\"text\"/></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">域名/URL/IP：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input class=\"input-big\" name=\"webPage\" type=\"text\"></input></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">生效起始时间 ：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"effectTimeBefore\" type=\"text\" class=\"easyui-datebox input-big\"></input></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">生效截止时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"effectTimeAfter\" type=\"text\" class=\"easyui-datebox input-big\"></input></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t\t<tr>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">过期起始时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"pastTimeBefore\" type=\"text\" class=\"easyui-datebox input-big\"></input></td>\r\n");
      out.write("\t\t    \t\t\t<th width=\"100\">过期截止时间：</th>\r\n");
      out.write("\t\t    \t\t\t<td><input name=\"pastTimeAfter\" type=\"text\" class=\"easyui-datebox input-big\"></input></td>\r\n");
      out.write("\t\t    \t\t</tr>\r\n");
      out.write("\t\t    \t</table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"add-save\">\r\n");
      out.write("\t\t   \t<a href=\"javascript:void(0);\" id=\"advanceSearchSubmit\" class=\"easyui-linkbutton\" >查询</a>\r\n");
      out.write("\t\t   \t<a href=\"javascript:void(0);\" id=\"advanceSearchCancel\" class=\"easyui-linkbutton\" onclick=\"javascript:$('#advanceSearch-dlg').dialog('close')\">关闭</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- 高级搜索  end -->\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
