/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-13 11:15:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.public_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class common2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("<link rel=\"stylesheet\" id=\"linktheme\" type=\"text/css\" href=\"js/easyui/themes/rzx-ui/easyui.css\">\r\n");
      out.write(" -->\r\n");
      out.write("<link rel=\"stylesheet\" id=\"linktheme\" type=\"text/css\" href=\"js/sysui/css/");
      out.print(request.getSession().getAttribute("layout") );
      out.write('/');
      out.print(request.getSession().getAttribute("skin") );
      out.write("/easyui.css\"> \r\n");
      out.write("<link rel=\"stylesheet\" id=\"linkskin\" type=\"text/css\" href=\"js/sysui/css/");
      out.print(request.getSession().getAttribute("layout") );
      out.write('/');
      out.print(request.getSession().getAttribute("skin") );
      out.write("/comm.css\">\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"js/sysui/css/");
      out.print(request.getSession().getAttribute("layout") );
      out.write('/');
      out.print(request.getSession().getAttribute("skin") );
      out.write("/style.css\"> \r\n");
      out.write("<link rel=\"stylesheet\" id=\"linkskin\" type=\"text/css\" href=\"js/easyui/themes/rzx-ui/scrollbar.css\">\r\n");
      out.write("<!-- 皮肤设置 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/global-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/secord.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/isotope.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/plugs/poshytip/tip-yellowsimple/tip-yellowsimple.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easyui/jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/rzx-js/scrollbar.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.json-2.4.min.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/rzx-js/jquery-rzx.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("/js/plugs/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/poshytip/jquery.poshytip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/constants.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/utils.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easyui/myload.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easyui/jquery.window.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/property.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/mask.js\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
