/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-13 11:15:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.br;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class brhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("\t<title>互联网资源首页</title>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/plugs/fusionmaps/FusionCharts.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/common/fusionMapsUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/br/charts.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/common/data.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/tm/netizenDatePickerUtil.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \r\n");
      out.write("<div class=\"xxaq\">\r\n");
      out.write("  <!-- 列表左边 -->\r\n");
      out.write("  <div class=\"zh-left br-left\" style=\"height:650px;\">\r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>本省主体备案网站总数</h2>\r\n");
      out.write("         <span class=\"br-Left\" id=\"websiteNum\">\r\n");
      out.write("            0\r\n");
      out.write("         </span>\r\n");
      out.write("         <!-- \r\n");
      out.write("         <span class=\"br-right\" >\r\n");
      out.write("            <b>存活数量</b>\r\n");
      out.write("            <label id=\"wensiteTrend\"><i id=\"wensiteTrends\" class=\"middle\"></i></label>\r\n");
      out.write("         </span>\r\n");
      out.write("          -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>IP地址总数</h2>\r\n");
      out.write("         <span class=\"br-Left\" style=\"height:55px; margin-top:20px\" id=\"ipNum\">\r\n");
      out.write("           0\r\n");
      out.write("         </span>\r\n");
      out.write("        <!--  <span class=\"br-right\">\r\n");
      out.write("            <b>趋势</b>\r\n");
      out.write("            <label id=\"ipTrend\"><i id=\"ipTrends\" class=\"middle\"></i></label>\r\n");
      out.write("            <div class=\"line\"></div>\r\n");
      out.write("            <b>占全国比例</b>\r\n");
      out.write("            <label id=\"comIpNum\">5.34%</label>\r\n");
      out.write("         </span> -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>未备案网站总数</h2>\r\n");
      out.write("         <span class=\"br-Left\" id=\"noRecordNum\">\r\n");
      out.write("           0\r\n");
      out.write("         </span>\r\n");
      out.write("         <span class=\"br-right\">\r\n");
      out.write("            <b>趋势</b>\r\n");
      out.write("            <label id=\"noRecordTrend\"><i id=\"noRecordTrends\" class=\"middle\"></i></label>\r\n");
      out.write("         </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>IDC自建机房总数</h2>\r\n");
      out.write("         <span class=\"br-Left\" id=\"houseNum\">\r\n");
      out.write("            0\r\n");
      out.write("         </span>\r\n");
      out.write("         <span class=\"br-right\">\r\n");
      out.write("            <b>集中区域</b>\r\n");
      out.write("            <label id=\"houseAreaName\">杭州</label>\r\n");
      out.write("         </span>\r\n");
      out.write("      </div>\r\n");
      out.write("       <!-- \r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>昨日活跃客户端IP总数</h2>\r\n");
      out.write("         <span class=\"br-Left\" id=\"clientIpNum\">\r\n");
      out.write("            0\r\n");
      out.write("         </span>\r\n");
      out.write("         <span class=\"br-right\">\r\n");
      out.write("            <b>活跃区域</b>\r\n");
      out.write("            <label id=\"clientIpAreaName\">杭州</label>\r\n");
      out.write("         </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>昨日全省DNS总解析量</h2>\r\n");
      out.write("         <span class=\"br-Left\" id=\"dnsNum\">\r\n");
      out.write("            0\r\n");
      out.write("         </span>\r\n");
      out.write("         <span class=\"br-right\">\r\n");
      out.write("            <b>趋势</b>\r\n");
      out.write("           \t<label id=\"dnsTrend\"><i id=\"dnsTrends\" class=\"middle\"></i></label>\r\n");
      out.write("         </span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"br-section\">\r\n");
      out.write("         <h2>昨日热点网站类别</h2>\r\n");
      out.write("         <span class=\"br-Left\" style=\"width:100%\" id=\"hotSite\">\r\n");
      out.write("          \t\t购物类\r\n");
      out.write("         </span>\r\n");
      out.write("      </div>\r\n");
      out.write("       -->\r\n");
      out.write("      \r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 列表内容 -->\r\n");
      out.write("  <div class=\"zh-mid\" style=\"height:650px;\">\r\n");
      out.write("     <dl class=\"br-dl map-big\">\r\n");
      out.write("      <dt>\r\n");
      out.write("         <div class=\"title-tab\" id=\"maps\">\r\n");
      out.write("            <span class=\"hover\" id=\"tab_house\">IDC机房</span>\r\n");
      out.write("            <span id=\"tab_website\">网站</span>\r\n");
      out.write("            <span id=\"tab_ip\">IP地址</span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <h1>地市分布统计</h1>\r\n");
      out.write("      </dt>\r\n");
      out.write("\t  <dd>\r\n");
      out.write("\t  \t <div class=\"zh-map\">\r\n");
      out.write("\t   \r\n");
      out.write("\t\t<!-- 地域地图 -->\r\n");
      out.write("\t\t<div class=\"house-map\" id=\"homeDataForMap\" style=\"height:400px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t   \r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("   <!-- \r\n");
      out.write("   <dl class=\"br-dl\">\r\n");
      out.write("      <dt>\r\n");
      out.write("         <h1>全省DNS解析量趋势统计</h1>\r\n");
      out.write("      </dt>\r\n");
      out.write("\t  <dd>\r\n");
      out.write("\t  \t<div id=\"container2\" style=\"height:245px;\"></div>\r\n");
      out.write("\t  </dd>\r\n");
      out.write("   </dl>\r\n");
      out.write("    -->\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("<!-- 列表右边 -->\r\n");
      out.write("<div class=\"zh-right\">\r\n");
      out.write("\t<!-- \r\n");
      out.write("   <dl class=\"br-dl map-min\">\r\n");
      out.write("      <dt>\r\n");
      out.write("         <h1>日活跃网站趋势统计</h1>\r\n");
      out.write("      </dt>\r\n");
      out.write("\t  <dd>\r\n");
      out.write("\t  \t<div id=\"container1\" style=\"height:210px; \"></div>\r\n");
      out.write("\t  </dd>\r\n");
      out.write("   </dl>\r\n");
      out.write("\t -->\r\n");
      out.write("   \r\n");
      out.write("   <dl class=\"br-dl map-min\">\r\n");
      out.write("      <dt>\r\n");
      out.write("         <div class=\"title-tab\" id=\"website\">\r\n");
      out.write("            <span class=\"hover\" id=\"tab_industry\">行业分类</span>\r\n");
      out.write("            <span id=\"tab_qzsp\">前置审批 </span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <h1>网站分类分布统计</h1>\r\n");
      out.write("      </dt>\r\n");
      out.write("\t  <dd>\r\n");
      out.write("\t  \t<div class=\"house-map\" id=\"cloumnCountData\" style=\"width:100%; height:210px\"></div>\r\n");
      out.write("\t  </dd>\r\n");
      out.write("   </dl>\r\n");
      out.write("   \r\n");
      out.write("   <dl class=\"br-dl top-height\" style=\"height: 389px;\">\r\n");
      out.write("      <dt>\r\n");
      out.write("         <div class=\"title-tab\" id=\"website_rank\">\r\n");
      out.write("            <span class=\"hover\" id=\"tab_in_province_zt\">本省主体</span>  <!-- 暂时注释，待数据录入后放开 -->\r\n");
      out.write("             <span  id=\"tab_in_province\">本省接入</span>\r\n");
      out.write("            <span id=\"tab_all\">全球 </span>\r\n");
      out.write("         </div>\r\n");
      out.write("         <h1>网站访问量排名</h1>\r\n");
      out.write("      </dt>\r\n");
      out.write("\t  <dd>\r\n");
      out.write("\t    <!-- 企业 -->\r\n");
      out.write(" \t\t<div class=\"layoutRight-huge top10 home-top\">\r\n");
      out.write("\t  \t\t<h2 class=\"right-title\"><span class=\"jczy-t2\">域名</span><span class=\"jczy-t3\">网站</span><span class=\"jczy-t4\">访问量</span><span class=\"jczy-t5\">排名趋势</span></h2>\r\n");
      out.write("\t\t\t<div class=\"houseData-huge\" id=\"typeCount\"></div>\r\n");
      out.write(" \t    </div> \r\n");
      out.write("\t  </dd>\r\n");
      out.write("   </dl>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modules/br/brhome.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/highstock/highstock.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modules/br/highstock_timerange.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
