/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-14 01:48:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.br;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class isVitualHost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" CONTENT=\"no-cache\">\r\n");
      out.write("\t\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugs/easyui-expands/datagrid-detailview1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/modules/br/isVitualHost.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\r\n");
      out.write("<!-- search -->\r\n");
      out.write("<div class=\"search\" data-options=\"region:'north'\"  class=\"breadCrumb-max\">\r\n");
      out.write("  <input id=\"hideEncodeIdcIspId\" type=\"hidden\" value=\"");
      out.print(request.getParameter("idcIspId"));
      out.write("\"/>\r\n");
      out.write("  <div class=\"search-left\">\r\n");
      out.write("\t  <span class=\"search-ico\"></span>\r\n");
      out.write("\t  <h1 class=\"search-title\">内容查询</h1>\r\n");
      out.write("\t  <form id=\"queryForm\">\r\n");
      out.write("\t  <div class=\"search-form\">\r\n");
      out.write("\t\t <span style=\"display: none;\">IP地址：<input name=\"virtualHostNetAddr\" id=\"virtualHostNetAddr\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t  \t <span>主机名称：<input name=\"virtualhostName\" id=\"virtualhostName\" type=\"text\" class=\"input-small\"></span>\r\n");
      out.write("\t\t <input id=\"hideHouseCity\" type=\"hidden\" name=\"houseCity\" value=\"");
      out.print(request.getParameter("areaCode"));
      out.write("\"/>\r\n");
      out.write("\t\t <input id=\"hideVitualType\" type=\"hidden\" name=\"virtualhostType\" value=\"");
      out.print(request.getParameter("virtualhostType"));
      out.write("\"/>\r\n");
      out.write("\t\t <input id=\"idcIspId\" type=\"hidden\" name=\"idcIspId\" value=\"");
      out.print(request.getParameter("idcIspId"));
      out.write("\"/>\r\n");
      out.write("\t\t <input name=\"legalFlag\" value=\"1\" type=\"hidden\">\r\n");
      out.write("\t\t <span class=\"search-button\"><a href=\"javascript:void(0)\" id=\"searchVitualHost\" iconCls=\"icon-search\">查询</a></span>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"search-right\">\r\n");
      out.write("    <span class=\"crumbs\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/menuNav.jsp", out, false);
      out.write("</span>\r\n");
      out.write("\t<span class=\"full\"><a href=\"javascript:void(0);\"></a></span>\r\n");
      out.write("\t<!--  <span class=\"tj\"><a href=\"javascript:void(0);\"></a></span>-->\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("\t<div class=\"list-add\">\r\n");
      out.write("\t <a href=\"javascript:void(0)\"  exportExcel=\"vitualHostGrid\" type=\"export\" fileName=\"vitualHost\" formId='queryForm' id=\"exportVitualHost\"><span class=\"export\"></span>导出</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 表格 -->\r\n");
      out.write("\t<div data-options=\"region:'center'\" border=\"false\" class=\"listCenter\">\r\n");
      out.write("\t\t<table id=\"vitualHostGrid\" ></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/excel.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
