/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-07-14 01:48:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.br;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vitualHostCount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/common2.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"js/jquery/jquery-powerFloat.js\"></script>\r\n");
      out.write("<script src=\"js/jquery/jquery.XYTipsWindow.2.8.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/fusionmaps/FusionCharts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modules/br/charts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common/fusionMapsUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modules/br/vitualHost_count.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".houseData-small.w2 .jczy-data-font{ width:100px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- tab -->\r\n");
      out.write("   <div class=\"breadCrumb-small\">\r\n");
      out.write("   <h1>\r\n");
      out.write("   \r\n");
      out.write("     <div class=\"tab-button housecount-tab\">\r\n");
      out.write("\t     <span id=\"all\" class=\"tab-button-left tab-button-hover\"><i class=\"ico-all\"></i>全部</span>\r\n");
      out.write("\t     <span id=\"gx\" class=\"tab-button-mid\"><i class=\"ico-gx\"></i>共享式</span>\r\n");
      out.write("\t     <span id=\"zy\" class=\"tab-button-mid\"><i class=\"ico-zy\"></i>专用式</span>\r\n");
      out.write("\t     <span id=\"yxn\" class=\"tab-button-right\"><i class=\"ico-yxn\"></i>云虚拟</span>\r\n");
      out.write("\t  </div>\r\n");
      out.write("  \r\n");
      out.write("  </h1>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"search-right\">\r\n");
      out.write("    \t<span class=\"crumbs\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../../public/menuNav.jsp", out, false);
      out.write("</span>\r\n");
      out.write("\t\t<span class=\"full\"><a href=\"javascript:void(0);\" title=\"全屏\"></a></span>\r\n");
      out.write("\t\t<span class=\"return-list\"><a href=\"javascript:void(0);\"></a></span>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("  <input type='hidden' id='vitualType' name='vitualType'>\r\n");
      out.write("  <input type='hidden' id='areaCode' name='areaCode'>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("     <!-- 地图 -->\r\n");
      out.write("     <div class=\"layoutLeft-small\">\r\n");
      out.write("\t    <h2 class=\"left-title\"><span id='hintInfo'>虚拟主机地市分布统计>全部</span>\r\n");
      out.write("\t     <i class=\"tip\">\r\n");
      out.write("\t\t\t<div class=\"tip-show\">\r\n");
      out.write("\t\t\t该统计向您展示虚拟主机在地市的分布情况。通过该统计可以知道那个地区的虚拟机架设的比较多。\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t       </i>\r\n");
      out.write("\t    </h2>\r\n");
      out.write("\t\t<div class=\"house-map\" id=\"dataForMap\" style=\"height: 410px;\"></div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t \r\n");
      out.write("\t <!-- 城市 -->\r\n");
      out.write("\t <div id=\"cityCount\" class=\"layoutRight-small\">\r\n");
      out.write("\t    <h2 class=\"right-title\"><span class=\"jczy-t1\">地市</span><span class=\"jczy-t2\">数量</span></h2>\r\n");
      out.write("\t\t<div class=\"houseData-small\"></div>\r\n");
      out.write("\t\t<h3 class=\"jczy-data-more\"></h3>\r\n");
      out.write("\t </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\">\t \r\n");
      out.write("\t <!-- 分布 -->\r\n");
      out.write("     <div class=\"layoutLeft-small\">\r\n");
      out.write("\t    <h2 class=\"left-title\"><span>虚拟主机企业分布统计 </span>\r\n");
      out.write("\t     <i class=\"tip\">\r\n");
      out.write("\t\t\t<div class=\"tip-show\">\r\n");
      out.write("\t\t\t 该统计将向您展示本省所有虚拟机在接入商的企业的分布情况。\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t       </i>\r\n");
      out.write("\t    </h2>\r\n");
      out.write("\t\t<div class=\"house-map\" id='dataForColumn' style=\"height: 390px;\"></div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t \r\n");
      out.write("\t <!-- 企业 -->\r\n");
      out.write("\t <div id='qyCount' class=\"layoutRight-small\">\r\n");
      out.write("\t    <h2 class=\"right-title\"><span class=\"jczy-t1\">企业1</span><span class=\"jczy-t2\">数量</span></h2>\r\n");
      out.write("\t\t<div class=\"houseData-small w2\"></div>\r\n");
      out.write("\t\t<h3 class=\"jczy-data-more\"></h3>\r\n");
      out.write("\t </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugs/highcharts/highcharts.js\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
